url: "https://simme.dev"
baseurl: ""

heading: simme.dev
content: 
copyright:  
  year: © 2023
  msg: Simon Aronsson 

privatelinks:
  title: Private or Broken Links
  msg: The page you're looking for is either not available or private!

preferences:
  search:
    enabled: true
  wiki_style_link: 
    enabled: true
  pagepreview: 
    enabled: true
  backlinks:
    enabled: true
  homepage: 
    enabled: true

encoding: utf-8
mermaid: true
theme: null
plugins:
  - jekyll-diagrams
  - jekyll-feed 
  - jekyll-sitemap 
  - jekyll-tidy

collections:
    notes:
      output: true
      permalink: /note/:title

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: katex
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge
  
sass:
  style: compressed

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: Post
      permalink: /post/:title
      content-type: post
  - scope:
      path: ""
      type: notes
    values:
      layout: Post
      content-type: notes

exclude:
  - _notes/000 Inbox
  - _notes/200 Private
  - _notes/300 Templates
  - _notes/Private
  - _notes/old
