baseURL = "https://simme.dev/"
languageCode = "en-us"
title = "Simon Aronsson"
theme = "paper"
googleAnalytics = "UA-155244210-1"

[params]
env = "production"

[menu]
[[menu.main]]
identifier = "about"
name = "about"
url = "/about"

[[menu.main]]
identifier = "uses"
name = "uses"
url = "/uses"

[[menu.main]]
identifier = "videos"
name = "videos"
url = "/videos"

[[menu.main]]
identifier = "projects"
name = "projects"
url = "/projects"