baseURL: 'https://simme.dev/'
title: Simon Aronsson
languageCode: en-us
rssLimit: 20

author:
  name: Simon Aronsson
  email: simme@arcticbit.se

googleAnalytics: UA-155244210-1

params:
  env: production

markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
    - identifier: about
      weight: 10
      name: about
      url: /about
    - identifier: speaking
      weight: 20
      name: speaking
      url: /speaking
    - identifier: videos
      weight: 30
      name: videos
      url: /videos
    # - identifier: podcasts
    #   weight: 40
    #   name: podcasts
    #   url: /podcasts
    - identifier: projects
      weight: 50
      name: projects
      url: /projects
    - identifier: uses
      weight: 60
      name: uses
      url: /uses
