baseURL = "https://simme.dev/"
languageCode = "en-us"
title = "Simon Aronsson"
theme = "paper"
googleAnalytics = "UA-155244210-1"

[params]
env = "production"

[menu]
[[menu.main]]
identifier = "about"
name = "about"
url = "/about"

[[menu.main]]
identifier = "videos"
name = "videos"
url = "/videos"